// Enrich the editorial catalogue with checked calendar data; no network requests in visitors' browsers.
const CALENDARS=typeof CALENDAR_DATA==='undefined'?{records:{},schedule:{active:false}}:CALENDAR_DATA;
const TODAY=new Intl.DateTimeFormat('en-CA',{timeZone:'Australia/Sydney',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
for(const show of SHOWS){const record=CALENDARS.records[show.id];if(record?.sessions?.length){show.sessions=record.sessions;show.calendarCoverage=record.coverage;show.calendarCheckedAt=record.calendarCheckedAt;show.calendarSource=record.sourceUrl;}}
function checkedDate(value){return value?new Date(value).toLocaleString(locale==='zh'?'zh-CN':'en-AU',{timeZone:'Australia/Sydney',year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):T('Not yet checked','尚未检查');}
function coverageText(s){if(s.calendarCoverage==='published')return T(`${s.sessions.length} currently published performances · checked list, not a guaranteed season total`,`${s.sessions.length} 场当前已公布演出 · 不保证为全季最终总数`);return s.sessionsComplete?T(`${s.sessions.length} published performances this season`,`本季已公布 ${s.sessions.length} 场`):s.sessions.length?T(`${s.sessions.length} sampled performances · not the season total`,`已录入 ${s.sessions.length} 场 · 非全季总数`):T('Individual performances not yet available','尚未取得逐场日历');}
function calendarRows(s){const groups={};for(const t of s.sessions)(groups[t[0].slice(0,7)]??=[]).push(t);return Object.entries(groups).map(([month,rows])=>`<details class="calendar-month" open><summary>${month} · ${T(`${rows.length} performances`,`${rows.length} 场`)}</summary>${rows.map(t=>`<div class="session-row"><strong>${day(t[0])}</strong><span>${t[1]}</span><span>${esc(t[2]==='Preview'?T('Preview','预演'):t[2]==='Sold out'?T('Sold out when checked','核对时售罄'):label(t[2]))}</span></div>`).join('')}</details>`).join('');}
function calendarNote(s){const r=CALENDARS.records[s.id];const stale=s.calendarCheckedAt&&Date.now()-Date.parse(s.calendarCheckedAt)>48*3600000;return `<p class="subtle">${T('Calendar checked: ','场次核对时间：')}${checkedDate(s.calendarCheckedAt)} ${T('(Sydney time). Availability can change.','（悉尼时间）。余票可能变化。')}${s.calendarSource?' '+ext(s.calendarSource,T('Calendar source','日历来源')):''}</p>${stale||r?.status==='failed'?`<p class="notice">${T('Refresh overdue or unsuccessful. Showing the last checked dates; confirm with the official seller.','更新已逾期或未成功。当前保留上次核对的日期，请向官方确认。')}</p>`:''}`;}
function updatesPanel(){const all=Object.entries(CALENDARS.records);return `<section class="block"><h2>${T('Calendar updates','场次更新')}</h2><p>${CALENDARS.schedule.active?T('Source checking is scheduled daily.','已安排每日来源检查。'):T('Scheduled checking is not enabled.','尚未启用定时检查。')} ${T('Last run: ','上次运行：')}${checkedDate(CALENDARS.lastRunAt)}</p><p class="subtle">${T('A successful page check does not mean its full calendar is available. Restricted booking systems require a supported feed or authorisation.','网页检查成功不代表已取得完整日历。受限票务系统仍需可用的数据接口或授权。')}</p><div class="update-list">${all.map(([id,r])=>{const s=SHOWS.find(s=>s.id===id);if(!s)return '';return `<div class="source-row"><a href="#/show/${s.id}">${esc(s.title)}</a><p>${coverageText(s)}<br>${T('Calendar checked: ','日历核对：')}${checkedDate(r.calendarCheckedAt)}</p><span class="tag">${r.status==='failed'?T('Refresh failed','更新失败'):r.calendarRestriction?T('Booking calendar restricted','票库接入受限'):r.coverage==='published'?T('Calendar refresh connected','日历更新已接入'):T('Partial / page checks','部分场次／页面检查')}</span></div>`;}).join('')}</div></section>`;}
