// Shared discovery surface. Venue-specific seasons retain their original provenance.
const browseStates={sydney:{q:'',genre:'all',scale:'all',venue:'all',period:'all',pick:'',sort:'recommended',archive:false,page:1},melbourne:{q:'',genre:'all',scale:'all',venue:'all',period:'all',pick:'',sort:'recommended',archive:false,page:1}};
let browseCity='sydney';
const browsePath=(kind='',id='')=>`#/${browseCity==='melbourne'?'melbourne/':''}${kind}${id?'/'+id:''}`;
const browseToday=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Australia/'+(browseCity==='melbourne'?'Melbourne':'Sydney'),year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const addDays=(day,n)=>{const d=new Date(day+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);};
function dateWindow(period,pick,today=browseToday()){
 if(period==='today')return [today,today];
 if(period==='weekend'){const weekday=new Date(today+'T12:00:00Z').getUTCDay();const saturday=addDays(today,weekday===0?-1:weekday===6?0:6-weekday);return [saturday,addDays(saturday,1)];}
 if(period==='next7')return [today,addDays(today,6)];
 if(period==='pick'&&/^\d{4}-\d{2}-\d{2}$/.test(pick))return [pick,pick];
 if(/^\d{4}-\d{2}$/.test(period))return [period+'-01',addDays(new Date(Date.UTC(Number(period.slice(0,4)),Number(period.slice(5)),1)).toISOString().slice(0,10),-1)];
 return null;
}
const browseShows=()=>browseCity==='melbourne'?MELBOURNE_SHOWS:SHOWS;
const browseVenues=()=>browseCity==='melbourne'?MELBOURNE_VENUES:VENUES;
const browseVenue=s=>browseVenues().find(v=>v.id===s.venue);
function showState(s,today=browseToday()){
 if(s.dateNeedsReview)return T('Dates under review','演期待复核');
 if(s.end<today)return T('Ended','已结束');
 if(s.start<=today&&s.end<=addDays(today,30))return T('Closing soon','即将闭幕');
 if(s.start<=today)return T('On now','正在上演');
 if(s.start<=addDays(today,30))return T('Opening soon','即将开演');
 return T('Upcoming','后续演出');
}
function showPrice(s){return Number.isFinite(s.price)&&s.price>=0?T(`From $${s.price}`,`$${s.price} 起`):T('Check official price','查看官方票价');}
function discoveryCard(s){const v=browseVenue(s),shown=browseCity==='sydney'?displayShow(s):s;return `<article class="show-card discovery-card"><a class="art" href="${browsePath('show',s.id)}" tabindex="-1" aria-hidden="true">${s.image?`<img src="${esc(s.image)}" alt="" loading="lazy" width="480" height="640">`:''}<div class="poster-fallback" ${s.image?'hidden':''}><span>${esc(label(s.genre))}</span><strong>${esc(s.title)}</strong><small>${esc(v.name)}</small></div></a><div class="card-body"><div class="card-top"><span class="tag ${cls(s.genre)}">${esc(label(s.genre))}</span><span class="status">${showState(s)}</span></div><h3><a href="${browsePath('show',s.id)}">${esc(shown.title)}</a></h3><a class="venue-link" href="${browsePath('venue',v.id)}">${esc(v.name)}<span>${esc(v.area)}</span></a><p class="card-date">${day(s.start)} – ${day(s.end)}</p><div class="card-meta">${ext(s.booking||s.source,showPrice(s),'price-link')}${ext(s.source,T('Official listing','官方详情'),'official-link')}</div></div></article>`;}
function recommendationSets(today=browseToday()){
 const live=browseShows().filter(s=>!s.dateNeedsReview&&s.end>=today&&s.start<=addDays(today,90)),weekend=dateWindow('weekend','',today);
 const ranked=rankShows(live,today,browseCity);
 return [
 {key:'current',en:'On now',zh:'正在上演',items:ranked.filter(s=>s.start<=today)},
 {key:'weekend',en:'This weekend',zh:'这个周末',items:ranked.filter(s=>s.start<=weekend[1]&&s.end>=weekend[0])},
 {key:'opening',en:'Opening soon',zh:'即将开演',items:ranked.filter(s=>s.start>today&&s.start<=addDays(today,30)).sort((a,b)=>a.start.localeCompare(b.start))},
 {key:'closing',en:'Closing soon',zh:'即将闭幕',items:ranked.filter(s=>s.start<=today&&s.end<=addDays(today,30)).sort((a,b)=>a.end.localeCompare(b.end))},
 {key:'musicals',en:'Musicals',zh:'音乐剧',items:ranked.filter(s=>s.genre==='音乐剧')},
 {key:'plays',en:'Plays',zh:'话剧',items:ranked.filter(s=>s.genre==='话剧')}
 ];
}
function recommendPage(){shell('recommend',`<div class="discovery-intro"><p class="eyebrow">${browseCity==='melbourne'?'THE MELBOURNE EDIT':'THE SYDNEY EDIT'}</p><h1>${T('What’s on','近期演出')}</h1><p class="subtle">${T('Musicals, plays and more, across the city.','发现这座城市的音乐剧、话剧与更多舞台演出。')}</p></div><div class="recommend-sections">${recommendationSets().map(group=>`<section class="recommend-section"><div class="section-head"><h2>${T(group.en,group.zh)}</h2><a href="${browsePath('catalogue')}?group=${group.key}" class="see-all">${T('See all →','查看全部 →')}</a></div>${group.key==='weekend'?`<p class="date-note">${T('Seasons overlapping this weekend. Check individual performance dates.','演期覆盖本周末；具体场次请查看官方日期。')}</p>`:''}<div class="poster-grid">${group.items.length?group.items.slice(0,4).map(discoveryCard).join(''):`<p class="section-empty">${T('No reviewed shows in this section yet.','这一组暂无已核实的演出。')}</p>`}</div></section>`).join('')}</div>${browseCity==='melbourne'?melAnnouncements():''}`);}
function discoveryChrome(){document.documentElement.lang=locale==='en'?'en-AU':'zh-CN';const labels={recommend:T('What’s on','近期演出'),catalogue:T('Discover','发现演出'),venues:T('Venues','剧院')};document.querySelectorAll('[data-nav]').forEach(a=>{a.textContent=labels[a.dataset.nav];a.href=browsePath(a.dataset.nav==='recommend'?'':a.dataset.nav);});$('#city-picker').value=browseCity;$('#language').textContent=locale==='en'?'中文':'English';$('#language').setAttribute('aria-label',T('Switch to Chinese','切换到英文'));$('nav').setAttribute('aria-label',T('Main navigation','主导航'));$('.skip').textContent=T('Skip to content','跳至内容');$('#city-picker').setAttribute('aria-label',T('Choose city','选择城市'));document.querySelectorAll('.brand').forEach(a=>a.href=browsePath());$('footer').innerHTML=`<div><a class="brand" href="${browsePath()}">theatre<span>diary.</span></a><p>${T('Discover theatre across Sydney and Melbourne.','发现悉尼与墨尔本的舞台演出。')}</p></div><div class="footer-links"><a href="${browsePath('about')}">${T('About','关于')}</a><a href="${browsePath('sources')}">${T('Data sources','数据来源')}</a><a href="${browsePath('contact')}">${T('Contact','联系')}</a><small>© 2026 Theatre Diary</small></div>`;}
// Filters stay on this device, so returning from a show keeps the catalogue context.
try{for(const city of ['sydney','melbourne']){const saved=JSON.parse(sessionStorage.getItem('theatre-browse-'+city)||'null');if(saved)Object.assign(browseStates[city],saved);}}catch{}
const browseScroll=new Map();let currentBrowseHash='',lastCatalogueHash='';
function persistBrowse(){try{sessionStorage.setItem('theatre-browse-'+browseCity,JSON.stringify(browseStates[browseCity]));}catch{}}
function browseFiltered(today=browseToday()){
 const f=browseStates[browseCity],range=dateWindow(f.period,f.pick,today),q=f.q.trim().toLowerCase();
 let shows=browseShows().filter(s=>{
 if(['cancelled','withdrawn'].includes(s.status))return false;
 const v=browseVenue(s),text=[s.title,s.company,s.genre,s.scale,v?.name,v?.area,s.desc,s.descZh,EN_SHOWS[s.id]?.desc].join(' ').toLowerCase();
 if(!text.includes(q)||f.genre!=='all'&&s.genre!==f.genre||f.scale!=='all'&&s.scale!==f.scale||f.venue!=='all'&&s.venue!==f.venue)return false;
 if(f.archive?s.end>=today:s.end<today)return false;
 if(range&&(s.start>range[1]||s.end<range[0]))return false;
 if(f.period==='current'&&s.start>today)return false;
 if(f.period==='opening'&&(s.start<=today||s.start>addDays(today,30)))return false;
 if(f.period==='closing'&&(s.start>today||s.end>addDays(today,30)))return false;
 return true;
 });
 if(f.sort==='date')return shows.sort((a,b)=>a.start.localeCompare(b.start)||a.title.localeCompare(b.title));
 if(f.sort==='closing')return shows.sort((a,b)=>a.end.localeCompare(b.end)||a.title.localeCompare(b.title));
 if(f.sort==='price')return shows.sort((a,b)=>(Number.isFinite(a.price)?a.price:Infinity)-(Number.isFinite(b.price)?b.price:Infinity)||a.start.localeCompare(b.start));
 return rankShows(shows,today,browseCity);
}
function advancedFields(prefix){const f=browseStates[browseCity],today=browseToday(),months=Array.from({length:12},(_,i)=>{const d=new Date(today+'T12:00:00Z');d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+i);return d.toISOString().slice(0,7);});const options=(pairs,value)=>pairs.map(([key,text])=>`<option value="${esc(key)}" ${key===value?'selected':''}>${esc(text)}</option>`).join('');return `<label>${T('Date','日期')}<select id="${prefix}-period">${options([['all',T('All dates','所有日期')],['today',T('Today','今天')],['weekend',T('This weekend','这个周末')],['next7',T('Next 7 days','未来 7 天')],['pick',T('Pick a date','选择日期')],['current',T('On now','正在上演')],['opening',T('Opening soon','即将开演')],['closing',T('Closing soon','即将闭幕')],...months.map(m=>[m,new Date(m+'-01T12:00:00Z').toLocaleDateString(locale==='en'?'en-AU':'zh-CN',{month:'long',year:'numeric'})])],f.period)}</select></label><label>${T('Pick a date','选择日期')}<input id="${prefix}-pick" type="date" value="${esc(f.pick)}"></label><label>${T('Genre','演出类别')}<select id="${prefix}-genre">${options([['all',T('All genres','所有类别')],...GENRES.map(g=>[g,label(g)])],f.genre)}</select></label><label>${T('Production type','制作类型')}<select id="${prefix}-scale">${options([['all',T('All productions','所有制作')],...['商业巡演','专业制作','独立制作','社区剧团'].map(g=>[g,label(g)])],f.scale)}</select></label><label>${T('Venue','剧院')}<select id="${prefix}-venue">${options([['all',T('All venues','所有剧院')],...rankVenues(browseVenues(),browseCity).map(v=>[v.id,v.name])],f.venue)}</select></label><label class="archive-toggle"><input id="${prefix}-archive" type="checkbox" ${f.archive?'checked':''}> ${T('Ended shows archive','已结束演出档案')}</label>`;}
function cataloguePage(){const f=browseStates[browseCity];shell('catalogue',`<div class="catalogue-heading"><h1>${T('Discover','发现演出')}</h1><p class="subtle">${browseCity==='melbourne'?'Melbourne':'Sydney'}</p></div><label class="catalogue-search"><span class="sr-only">${T('Search shows','搜索演出')}</span><input id="browse-search" type="search" value="${esc(f.q)}" placeholder="${T('Search shows, venues or suburbs…','搜索剧名、剧院或地区…')}"></label><div class="quick-filters"><button class="chip" data-period="today">${T('Today','今天')}</button><button class="chip" data-period="weekend">${T('This weekend','这个周末')}</button><button class="chip" data-period="next7">${T('Next 7 days','未来 7 天')}</button><button class="chip" data-genre="音乐剧">${T('Musicals','音乐剧')}</button><button class="chip" data-genre="话剧">${T('Plays','话剧')}</button><button class="chip" data-period="closing">${T('Closing soon','即将闭幕')}</button><button class="chip" id="pick-date">${T('Pick a date','选择日期')}</button><button class="chip mobile-more" id="more-filters">${T('More filters','更多筛选')}</button></div><section class="advanced-filters" aria-label="${T('Filters','筛选条件')}">${advancedFields('desktop')}</section><dialog id="filter-dialog" aria-labelledby="filter-title"><form method="dialog"><div class="sheet-head"><h2 id="filter-title">${T('Filters','筛选条件')}</h2><button class="text-button" value="cancel" aria-label="${T('Close filters','关闭筛选')}">✕</button></div><div class="sheet-fields">${advancedFields('sheet')}</div><div class="sheet-actions"><button class="btn outline" id="sheet-reset" type="button">${T('Reset','重置')}</button><button class="btn primary" id="sheet-apply" type="button">${T('Show results','查看结果')}</button></div></form></dialog><div class="results-head catalogue-results-head"><p id="browse-count" role="status" aria-live="polite"></p><div><label class="sr-only" for="browse-sort">${T('Sort','排序')}</label><select id="browse-sort" title="${T('Recommended prioritises major productions and key venues, balanced with season dates.','推荐排序优先大型制作和重点剧院，并考虑演期。')}"><option value="recommended">${T('Recommended','推荐排序')}</option><option value="date">${T('Opening soon','即将开演')}</option><option value="closing">${T('Closing soon','即将闭幕')}</option><option value="price">${T('Price ↑','价格 ↑')}</option></select><button class="text-button" id="browse-reset">${T('Reset','重置')}</button></div></div><p id="browse-date-note" class="date-note"></p><section id="browse-results" class="poster-grid catalogue-grid" aria-label="${T('Shows','演出列表')}"></section>`);
 $('#browse-search').oninput=e=>{f.q=e.target.value;f.page=1;catalogueResults();};
 $('#browse-sort').value=f.sort;$('#browse-sort').onchange=e=>{f.sort=e.target.value;f.page=1;catalogueResults();};
 const update=()=>{f.page=1;catalogueResults();};
 for(const key of ['period','pick','genre','scale','venue','archive'])$('#desktop-'+key).onchange=e=>{f[key]=key==='archive'?e.target.checked:e.target.value;if(key==='pick')f.period='pick';update();syncFilters();};
 document.querySelectorAll('[data-period]').forEach(b=>b.onclick=()=>{f.period=f.period===b.dataset.period?'all':b.dataset.period;update();syncFilters();});
 document.querySelectorAll('[data-genre]').forEach(b=>b.onclick=()=>{f.genre=f.genre===b.dataset.genre?'all':b.dataset.genre;update();syncFilters();});
 $('#more-filters').onclick=()=>openFilters();$('#pick-date').onclick=()=>{f.period='pick';syncFilters();openFilters();$('#sheet-pick').focus();};
 $('#sheet-apply').onclick=()=>{const pick=$('#sheet-pick');pick.required=$('#sheet-period').value==='pick';if(!pick.reportValidity())return;for(const key of ['period','pick','genre','scale','venue','archive'])f[key]=key==='archive'?$('#sheet-'+key).checked:$('#sheet-'+key).value;$('#filter-dialog').close();update();syncFilters();};
 $('#sheet-pick').onchange=()=>{$('#sheet-period').value='pick';};
 $('#sheet-reset').onclick=()=>{for(const key of ['period','genre','scale','venue'])$('#sheet-'+key).value='all';$('#sheet-pick').value='';$('#sheet-archive').checked=false;};$('#browse-reset').onclick=()=>{resetBrowse();cataloguePage();};
 syncFilters();catalogueResults();
}
function resetBrowse(){Object.assign(browseStates[browseCity],{q:'',genre:'all',scale:'all',venue:'all',period:'all',pick:'',sort:'recommended',archive:false,page:1});persistBrowse();}
function syncFilters(){const f=browseStates[browseCity];for(const prefix of ['desktop','sheet'])for(const key of ['period','pick','genre','scale','venue','archive']){const el=$('#'+prefix+'-'+key);if(el){if(key==='archive')el.checked=f[key];else el.value=f[key];}}document.querySelectorAll('[data-period]').forEach(b=>{const active=f.period===b.dataset.period;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active);});document.querySelectorAll('[data-genre]').forEach(b=>{const active=f.genre===b.dataset.genre;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active);});}
function openFilters(){syncFilters();$('#filter-dialog').showModal();}
function catalogueResults(){const f=browseStates[browseCity],all=browseFiltered(),visible=all.slice(0,f.page*18);persistBrowse();$('#browse-count').textContent=T(`${all.length} shows${f.archive?' · Archive':''}`,`${all.length} 条演出${f.archive?' · 历史档案':''}`);$('#browse-date-note').textContent=f.period==='all'?'':T('Filtered by season dates. Check the official listing for individual performances.','按演期筛选，具体开演日期请查看官方详情。');$('#browse-date-note').hidden=f.period==='all';$('#browse-results').innerHTML=(visible.length?visible.map(discoveryCard).join(''):`<div class="empty"><h2>${T('No matching shows','没有匹配的演出')}</h2><p>${T('Try another date or clear your filters.','试试其他日期，或清除筛选条件。')}</p><button id="clear-empty" class="btn outline">${T('Clear filters','清除筛选')}</button></div>`)+(all.length>visible.length?`<div class="more-row"><p class="subtle">${T(`${visible.length} of ${all.length} shows`,`${visible.length} / ${all.length} 条演出`)}</p><button id="browse-more" class="btn outline">${T('Show 18 more','再显示 18 条')}</button></div>`:'');$('#browse-more')?.addEventListener('click',()=>{f.page++;catalogueResults();});$('#clear-empty')?.addEventListener('click',()=>{$('#browse-reset').click();});}
function aboutPage(){shell('',`<article class="info-page"><p class="eyebrow">THEATRE DIARY</p><h1>${T('A place to find your next show.','发现下一场值得看的演出。')}</h1><p>${T('Theatre Diary brings together musicals, plays, dance, opera and independent and community productions across Sydney and Melbourne.','Theatre Diary 汇集悉尼与墨尔本的音乐剧、话剧、舞蹈、歌剧，以及独立和社区制作。')}</p><p>${T('Browse a few recommendations, search the catalogue or start with a venue. Book directly through the official listing.','可以从推荐逛起，也可以搜索剧目目录，或按剧院寻找演出。购票请通过官方页面。')}</p><h2>${T('Sources and updates','来源与更新')}</h2><p>${T('Listings come from official venues and producers. Community directories help us discover smaller productions. Daily checks are scheduled for selected sources; coverage and calendar detail vary by source.','演出资料以剧院和制作方官网为准，社区目录帮助发现较小制作。部分来源已安排每日检查；来源覆盖和逐场日历完整度有所不同。')}</p><p>${T('This is a growing catalogue, so a missing show does not mean it is not running. Season dates are not a promise of a performance every day. Prices, dates and availability should be confirmed with the organiser.','目录仍在扩展，未收录不代表没有演出。演期不代表每天都有场次；价格、日期及余票请以主办方为准。')}</p><a class="btn outline" href="${browsePath('sources')}">${T('View data sources','查看数据来源')}</a></article>`);}
function contactPage(){shell('',`<article class="info-page"><h1>${T('Contact','联系')}</h1><h2>${T('Missing show or a correction?','有遗漏或需要更正？')}</h2><p>${T('Include the show title, city and an official listing link when leaving project feedback.','反馈时请附上剧名、城市及官方演出链接。')}</p>${ext('https://github.com/daisyy777/my_theatre_diary/issues',T('Leave feedback on GitHub','在 GitHub 留下反馈'),'btn outline')}<p class="subtle">${T('Ticket changes, refunds and accessibility bookings are handled by the organiser or ticket seller. Use the official listing for their contact details.','改票、退款及无障碍购票由主办方或票务商处理，请通过官方页面联系。')}</p></article>`);}
function applyGroup(group){resetBrowse();const f=browseStates[browseCity];if(['current','weekend','opening','closing'].includes(group))f.period=group;if(group==='musicals')f.genre='音乐剧';if(group==='plays')f.genre='话剧';persistBrowse();}
route=function(){
 const raw=location.hash||'#/',[path,query]=raw.split('?'),parts=path.replace(/^#\/?/,'').split('/');
 browseCity=parts[0]==='melbourne'?'melbourne':'sydney';const offset=browseCity==='melbourne'?1:0,kind=parts[offset]||'',id=parts[offset+1];
 discoveryChrome();document.title=`Theatre Diary · ${browseCity==='melbourne'?'Melbourne':'Sydney'}`;
 if(!kind||kind==='recommend')recommendPage();
 else if(kind==='catalogue'||kind==='discover'){const group=new URLSearchParams(query||'').get('group');if(group&&raw!==lastCatalogueHash)applyGroup(group);cataloguePage();lastCatalogueHash=raw;}
 else if(kind==='show'){if(browseCity==='melbourne')melShow(id);else showDetail(id);const back=$('.breadcrumb');if(back){back.href=lastCatalogueHash&&lastCatalogueHash.includes(browseCity==='melbourne'?'melbourne/':'#/catalogue')?lastCatalogueHash:browsePath('catalogue');back.textContent=T('← Back to Discover','← 返回发现演出');}document.querySelectorAll('[data-nav]').forEach(a=>{if(a.dataset.nav==='catalogue')a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});}
 else if(kind==='venues')discoveryVenues();
 else if(kind==='venue')browseCity==='melbourne'?melVenueDetail(id):venueDetail(id);
 else if(kind==='sources')browseCity==='melbourne'?melSources():sourcesPage();
 else if(kind==='about')aboutPage();else if(kind==='contact')contactPage();else notFound();
 // Existing detail/source renderers are kept, but global chrome belongs to this shared surface.
 discoveryChrome();currentBrowseHash=raw;const y=browseScroll.get(raw)||0;
 window.requestAnimationFrame(()=>{if(currentBrowseHash===raw)window.scrollTo(0,y);});
};
window.addEventListener('scroll',()=>{if(currentBrowseHash)browseScroll.set(currentBrowseHash,window.scrollY);},{passive:true});
$('#city-picker').onchange=e=>{const newCity=e.target.value,old=browseCity;const kind=location.hash.includes('/catalogue')?'catalogue':location.hash.includes('/venues')?'venues':'';try{localStorage.setItem('theatre-city',newCity);}catch{}browseCity=newCity;const target=browsePath(kind);browseCity=old;location.hash=target;};
route();
function discoveryVenues(){const today=browseToday();shell('venues',`<div class="catalogue-heading"><h1>${T('Venues','剧院')}</h1><p class="subtle">${browseCity==='melbourne'?'Melbourne':'Sydney'}</p></div><div class="venue-grid">${rankVenues(browseVenues(),browseCity).map(v=>{const shows=browseShows().filter(s=>s.venue===v.id&&s.end>=today),now=shows.filter(s=>s.start<=today),next=shows.filter(s=>s.start>today).sort((a,b)=>a.start.localeCompare(b.start));return `<article class="venue-card"><p class="eyebrow">${esc(v.area)}</p><h3><a href="${browsePath('venue',v.id)}">${esc(v.name)} →</a></h3><p>${esc(v.address)}</p><div class="venue-counts"><span>${T(`${now.length} on now`,`${now.length} 条正在上演`)}</span><span>${T(`${next.length} upcoming`,`${next.length} 条后续演出`)}</span></div>${now[0]?`<p class="venue-programme"><strong>${T('On now','正在上演')}</strong><a href="${browsePath('show',now[0].id)}">${esc(now[0].title)}</a></p>`:''}${next[0]?`<p class="venue-programme"><strong>${T('Next up','接下来')}</strong><a href="${browsePath('show',next[0].id)}">${esc(next[0].title)}</a></p>`:''}${!shows.length?`<p>${T('No upcoming listing yet. Check the venue programme.','暂无后续条目，请查看剧院官方节目。')}</p>`:''}</article>`;}).join('')}</div>`);}
